/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package login;



import javax.swing.JOptionPane;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.DecimalFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Guillermo
 */
public class panel1 extends javax.swing.JPanel {
 // definir variables globales
    static Connection con  = null;
    
   
    
    /**
     * Creates new form panel1
     */
    public panel1() {
        initComponents();
        
          bG_botonVino.add(jRB_si);
          bG_botonVino.add(jRB_no);
          
        con  = BDCarne.Conexion_BD.Conectar(); // paquete.clase.metodo   
          
          
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bG_botonVino = new javax.swing.ButtonGroup();
        jLabel3 = new javax.swing.JLabel();
        jTCantidadPersonas = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTPresupuesto3 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jRB_si = new javax.swing.JRadioButton();
        jRB_no = new javax.swing.JRadioButton();
        jCheckBox2 = new javax.swing.JCheckBox();
        jCheckBox1 = new javax.swing.JCheckBox();
        jBPresupuesto = new javax.swing.JButton();
        jCheckBox3 = new javax.swing.JCheckBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        bt_Salir = new javax.swing.JButton();
        jTPresupuesto2 = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(500, 380));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("     ¡ Un Asado !");

        jTCantidadPersonas.setText("0");

        jLabel4.setText("Cantidad de Personas");

        jLabel5.setText("Total Presupuesto");

        jTPresupuesto3.setText("0");

        jLabel8.setText("Presupuesto por Persona");

        jLabel6.setText("Elección Carne");

        jLabel7.setText("Elección Vino");

        jRB_si.setText("Si");
        jRB_si.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRB_siActionPerformed(evt);
            }
        });

        jRB_no.setText("NO");

        jCheckBox2.setText("Pollo");

        jCheckBox1.setText("Vacuno");

        jBPresupuesto.setText("Calcular Presupuesto");
        jBPresupuesto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBPresupuestoActionPerformed(evt);
            }
        });

        jCheckBox3.setText("Cerdo");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Carne", "Cantidad kg", "Temperatura", "Tiempo hr", "Precio $", "carbon kg"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        bt_Salir.setText("SALIR");
        bt_Salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_SalirActionPerformed(evt);
            }
        });

        jTPresupuesto2.setText("0");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addComponent(jCheckBox1)
                                    .addComponent(jCheckBox2)
                                    .addComponent(jCheckBox3))
                                .addGap(40, 40, 40)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jRB_no)
                                    .addComponent(jRB_si)
                                    .addComponent(jLabel7)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel4))
                                .addGap(34, 34, 34)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jTCantidadPersonas)
                                    .addComponent(jTPresupuesto3, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addGap(18, 18, 18)
                                .addComponent(jTPresupuesto2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                        .addComponent(jBPresupuesto)
                        .addGap(65, 65, 65)
                        .addComponent(bt_Salir, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(73, 73, 73))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 328, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(62, 62, 62)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jBPresupuesto, javax.swing.GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE)
                            .addComponent(bt_Salir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTCantidadPersonas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(jTPresupuesto3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(jTPresupuesto2, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(59, 59, 59)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jRB_si)
                            .addComponent(jCheckBox1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jCheckBox2)
                            .addComponent(jRB_no))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jCheckBox3)))
                .addContainerGap(13, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jRB_siActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRB_siActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRB_siActionPerformed

    private void jBPresupuestoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBPresupuestoActionPerformed
     
       DecimalFormat decimal = new DecimalFormat("##.#");
       DecimalFormat decimal2 = new DecimalFormat("##");
       String cad1 = jTPresupuesto3.getText();
       String cad2 = jTCantidadPersonas.getText();
       int x1=Integer.parseInt(cad1);
       int x2=Integer.parseInt(cad2);
       
       if(x2<=0){
            x2=1;
        }
                   double persona=x1/x2;
            jTPresupuesto2.setText(""+persona);

             
            
            
         String mensaje="Cantidad de Carne:\n";    
            
    if (persona<10000){        
           // Eleccion Tipo de Carne
     //    String mensaje="Cantidad de Carne:\n";
        if (jCheckBox1.isSelected()) {
            mensaje=mensaje+"Vacuno\n"+"Tipo: Abastero\n"+
                    "Cantidad: "+x2*0.5+" kg\n" + "Precio $"+decimal2.format((x2*0.5*3500))+"\n"+
                    "Cantidad Carbon:"+x2*0.5+"kg\n";
        }
        if (jCheckBox2.isSelected()) {
            mensaje=mensaje+"Pollo\n"+
                    "Cantidad: "+x2*0.5+" kg\n" + "Precio $"+decimal2.format((x2*0.5*3000))+"\n"+
                    "Cantidad Carbon:"+x2*0.5*1.5+"kg\n";       
        }
        if (jCheckBox3.isSelected()) {
            mensaje=mensaje+"Cerdo\n"+
                    "Cantidad: "+x2*0.5+" kg\n" + "Precio $"+decimal2.format((x2*0.5*4000))+"\n"+
                    "Cantidad Carbon:"+x2*0.5*1.5+"kg\n";
                
        } 
        
    }else{
       if(persona>=10000){
       // Eleccion Tipo de Carne
       //  String mensaje="Cantidad de Carne:\n";
        if (jCheckBox1.isSelected()) {
            mensaje=mensaje+"Vacuno\n"+"Tipo: Lomo Vetado\n"+
                    "Cantidad: "+x2*0.5+" kg\n" + "Precio $"+decimal2.format((x2*0.5*7000))+"\n"+
                    "Cantidad Carbon:"+x2*0.5+"kg\n";
        }
        if (jCheckBox2.isSelected()) {
            mensaje=mensaje+"Pollo\n"+
                    "Cantidad: "+x2*0.5+" kg\n" + "Precio $"+decimal2.format((x2*0.5*3000))+"\n"+
                    "Cantidad Carbon:"+x2*0.5+"kg\n";       
        }
        if (jCheckBox3.isSelected()) {
            mensaje=mensaje+"Cerdo\n"+
                    "Cantidad: "+x2*0.5+" kg\n" + "Precio $"+decimal2.format((x2*0.5*4000))+"\n"+
                    "Cantidad Carbon:"+x2*0.5+"kg\n";
                
        }      
        
       }
    }
            
        
   
        //Eleccion Vino
       String mensaje4="Vino elegido: ";
        
        if (jRB_si.isSelected()) {
            mensaje4=mensaje4+"Si \n";
         } else if (jRB_no.isSelected()) {
            mensaje4=mensaje4+"No ";
        }
        
        if(jRB_si.isSelected() && jCheckBox1.isSelected() ){
            mensaje4=mensaje4+"Vacuno: "+"Cabernet o Carmener o Syrah\n";
            
        }
        
        if(jRB_si.isSelected() && jCheckBox2.isSelected() ){
            mensaje4=mensaje4+"Pollo: "+" Pinot Noir\n";
            
        }
        
        if(jRB_si.isSelected() && jCheckBox3.isSelected() ){
            mensaje4=mensaje4+"Cerdo: "+"Viognier\n";
            
        }
        
        
        JOptionPane.showOptionDialog(
       null,              //Componente
        mensaje+mensaje4, // Mensaje
       "Se recomienda Elecciones Asado:" ,  //Titulo
       JOptionPane.DEFAULT_OPTION, //Tipo Opciones
       JOptionPane.INFORMATION_MESSAGE, // Tipo mensaje
       null, // Icono ninguno
       null, // Opciones Personalizadas
       null // Opcion por defecto
       );  
       
        
            
         
          if(persona<980){  
     JOptionPane.showOptionDialog(
       null,              //Componente
        "No tiene Saldo para comprar Carne", // Mensaje
       "Se recomienda tener mas dinero" ,  //Titulo
       JOptionPane.DEFAULT_OPTION, //Tipo Opciones
       JOptionPane.WARNING_MESSAGE, // Tipo mensaje
       null, // Icono ninguno
       null, // Opciones Personalizadas
       null // Opcion por defecto
     );
        }
        
        
   
        
        
      DefaultTableModel modelo = new DefaultTableModel(); //Creo un modelo de datos para un jtable
       //creo 4 columnas, Tipo de carne, cantidad, precio, cantidad de carbon
       // Estas son las columnas del JTable
       modelo.addColumn("Carne");
       modelo.addColumn("Cantidad kg");
       modelo.addColumn("Temperatura");
       modelo.addColumn("Tiempo hr");
       modelo.addColumn("Precio $");
       modelo.addColumn("Carbon kg");
       jTable1.setModel(modelo); //         

        try {
            Statement st = con.createStatement();
    //Recorro el ResultSet que contiene los resultados.
    try (ResultSet rs = st.executeQuery("SELECT *"
            + " FROM datos_vacuno")) {
        //Recorro el ResultSet que contiene los resultados.
        while (rs.next()) {
            Object[]  ob=new Object[6];//Crea un vector
            //para almacenar los valores del ResultSet
            ob[0]=(rs.getString(1));
            ob[1]=decimal.format(Double.parseDouble((rs.getString(2)))/Double.parseDouble((rs.getString(4)))*x2);
            ob[2]=(rs.getString(8));
            ob[3]=(rs.getString(6));
            ob[4]=decimal2.format(Double.parseDouble((rs.getString(2)))/Double.parseDouble((rs.getString(4)))*x2*Double.parseDouble((rs.getString(10))));
            ob[5]=decimal.format(Double.parseDouble((rs.getString(9)))*Double.parseDouble((rs.getString(2)))/Double.parseDouble((rs.getString(4)))*x2);
            //añado el modelo a la tabla
            modelo.addRow(ob);
        }
        
        //Cierra el ResultSet
    }
            } catch (SQLException ex) {
            Logger.getLogger(panel1.class.getName()).log(Level.SEVERE, null, ex);
        } 

 
        
    
       
       
       
            
    }//GEN-LAST:event_jBPresupuestoActionPerformed

    private void bt_SalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_SalirActionPerformed
       try {
            con.close(); // cierra conexion
            System.exit(0); // cierra la ventana
        } catch (SQLException ex) {
            Logger.getLogger(panel1.class.getName()).log(Level.SEVERE, null, ex);
        } 
        
        
    }//GEN-LAST:event_bt_SalirActionPerformed


       
       
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup bG_botonVino;
    private javax.swing.JButton bt_Salir;
    private javax.swing.JButton jBPresupuesto;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JCheckBox jCheckBox3;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JRadioButton jRB_no;
    private javax.swing.JRadioButton jRB_si;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTCantidadPersonas;
    private javax.swing.JLabel jTPresupuesto2;
    private javax.swing.JTextField jTPresupuesto3;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
