/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package login;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

/**
 *
 * @author Guillermo
 */
public class ventana2 extends javax.swing.JFrame implements ActionListener{

    /**
     * Creates new form ventana2
     */
    panel1 panel1 = new panel1();
    panel3 panel2 = new panel3();
    
    public ventana2() {
        initComponents();
       
      
        
        jPContenedor.add(panel1);
        setSize(660, 500); 
         setLocationRelativeTo(null);
        setResizable(false);
        panel1.setVisible(true);
        panel2.setVisible(false);
        deshabilitarBotones();
        jBAnterior.addActionListener(this);
        jBSiguiente.addActionListener(this);
    }

    
    private void deshabilitarBotones(){
        
     if(panel1.isVisible()){
         jBAnterior.setEnabled(false);
         jBSiguiente.setEnabled(true);
         
     } else if(panel2.isVisible()){
       jBAnterior.setEnabled(true);
         jBSiguiente.setEnabled(false);  
         
     }  
        
        
    }
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bG_botonVino = new javax.swing.ButtonGroup();
        jPContenedor = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jBAnterior = new javax.swing.JButton();
        jBSiguiente = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPContenedor.setPreferredSize(new java.awt.Dimension(440, 380));
        jPContenedor.setLayout(new java.awt.BorderLayout());

        jBAnterior.setText("Anterior");
        jPanel1.add(jBAnterior);

        jBSiguiente.setText("Siguiente");
        jPanel1.add(jBSiguiente);

        jPContenedor.add(jPanel1, java.awt.BorderLayout.PAGE_END);

        getContentPane().add(jPContenedor, java.awt.BorderLayout.CENTER);
        jPContenedor.getAccessibleContext().setAccessibleName("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ventana2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ventana2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ventana2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ventana2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ventana2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup bG_botonVino;
    private javax.swing.JButton jBAnterior;
    private javax.swing.JButton jBSiguiente;
    private javax.swing.JPanel jPContenedor;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables

    @Override
    public void actionPerformed(ActionEvent e) {
    //    throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    
    Object evt = e.getSource();
    
    if(evt.equals(jBAnterior)){
      panel2.setVisible(false);
      panel1.setVisible(true); 
      jPContenedor.add(panel1);
      jPContenedor.validate();
      deshabilitarBotones();
      
    }else if(evt.equals(jBSiguiente)){
      
      panel1.setVisible(false);
      panel2.setVisible(true); 
      jPContenedor.add(panel2);
      jPContenedor.validate();
      deshabilitarBotones();       
        
    }
    
    
    
    }
}
